/* Generated by Yosys 0.63 (git sha1 70a11c6bf0e8dd669f56c7da3587f78b405138e2, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "ff_sync" *)
(* src = "rtl/ff_sync.sv:2.1-26.10" *)
module \$paramod\ff_sync\WIDTH=s32'00000000000000000000000000000101 (clk, rst_n, din, dout);
  (* src = "rtl/ff_sync.sv:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "rtl/ff_sync.sv:4.17-4.22" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/ff_sync.sv:5.29-5.32" *)
  input [4:0] din;
  wire [4:0] din;
  (* src = "rtl/ff_sync.sv:6.30-6.34" *)
  output [4:0] dout;
  reg [4:0] dout;
  (* src = "rtl/ff_sync.sv:8.18-8.20" *)
  reg [4:0] q1;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:18.1-25.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[0] <= 1'h0;
    else dout[0] <= q1[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:18.1-25.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[1] <= 1'h0;
    else dout[1] <= q1[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:18.1-25.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[2] <= 1'h0;
    else dout[2] <= q1[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:18.1-25.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[3] <= 1'h0;
    else dout[3] <= q1[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:18.1-25.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dout[4] <= 1'h0;
    else dout[4] <= q1[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:9.1-16.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) q1[0] <= 1'h0;
    else q1[0] <= din[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:9.1-16.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) q1[1] <= 1'h0;
    else q1[1] <= din[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:9.1-16.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) q1[2] <= 1'h0;
    else q1[2] <= din[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:9.1-16.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) q1[3] <= 1'h0;
    else q1[3] <= din[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/ff_sync.sv:9.1-16.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) q1[4] <= 1'h0;
    else q1[4] <= din[4];
endmodule

(* dynports =  1  *)
(* hdlname = "rd_ptr" *)
(* src = "rtl/rd_ptr.sv:2.1-20.10" *)
module \$paramod\rd_ptr\ADDR_WIDTH=s32'00000000000000000000000000000100 (rd_clk, rd_rst_n, rd_en, empty, b_rd_ptr, gr_rd_ptr);
  (* src = "rtl/rd_ptr.sv:3.17-3.23" *)
  input rd_clk;
  wire rd_clk;
  (* src = "rtl/rd_ptr.sv:4.17-4.25" *)
  input rd_rst_n;
  wire rd_rst_n;
  (* src = "rtl/rd_ptr.sv:5.17-5.22" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/rd_ptr.sv:6.17-6.22" *)
  input empty;
  wire empty;
  (* src = "rtl/rd_ptr.sv:7.33-7.41" *)
  output [4:0] b_rd_ptr;
  reg [4:0] b_rd_ptr;
  (* src = "rtl/rd_ptr.sv:8.33-8.42" *)
  output [4:0] gr_rd_ptr;
  wire [4:0] gr_rd_ptr;
  (* src = "rtl/rd_ptr.sv:15.14-15.29" *)
  wire _00_;
  (* src = "rtl/rd_ptr.sv:15.23-15.29" *)
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _04_;
  (* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _05_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:11.1-18.4" *)
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) b_rd_ptr[0] <= 1'h0;
    else if (_00_) b_rd_ptr[0] <= _03_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:11.1-18.4" *)
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) b_rd_ptr[1] <= 1'h0;
    else if (_00_) b_rd_ptr[1] <= gr_rd_ptr[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:11.1-18.4" *)
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) b_rd_ptr[2] <= 1'h0;
    else if (_00_) b_rd_ptr[2] <= _04_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:11.1-18.4" *)
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) b_rd_ptr[3] <= 1'h0;
    else if (_00_) b_rd_ptr[3] <= _04_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/rd_ptr.sv:11.1-18.4" *)
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) b_rd_ptr[4] <= 1'h0;
    else if (_00_) b_rd_ptr[4] <= _04_[4];
  assign _03_[0] = ~b_rd_ptr[0];
  assign gr_rd_ptr[1] = b_rd_ptr[2] ^(* src = "rtl/rd_ptr.sv:19.20-19.46" *)  b_rd_ptr[1];
  assign gr_rd_ptr[2] = b_rd_ptr[3] ^(* src = "rtl/rd_ptr.sv:19.20-19.46" *)  b_rd_ptr[2];
  assign gr_rd_ptr[3] = b_rd_ptr[4] ^(* src = "rtl/rd_ptr.sv:19.20-19.46" *)  b_rd_ptr[3];
  assign gr_rd_ptr[0] = b_rd_ptr[1] ^(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  b_rd_ptr[0];
  assign _04_[2] = b_rd_ptr[2] ^(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _02_[1];
  assign _04_[3] = b_rd_ptr[3] ^(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _02_[2];
  assign _04_[4] = b_rd_ptr[4] ^(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _02_[3];
  assign _02_[2] = b_rd_ptr[2] &(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _02_[1];
  assign _02_[3] = _05_ &(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _02_[1];
  assign _05_ = b_rd_ptr[3] &(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  b_rd_ptr[2];
  assign _02_[1] = b_rd_ptr[1] &(* src = "rtl/rd_ptr.sv:16.21-16.33|rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  b_rd_ptr[0];
  assign _01_ = ~(* src = "rtl/rd_ptr.sv:15.23-15.29" *) empty;
  assign _00_ = rd_en &(* src = "rtl/rd_ptr.sv:15.14-15.29" *)  _01_;
  assign _03_[31:1] = { 27'h0000000, b_rd_ptr[4:1] };
  assign { _04_[31:5], _04_[1:0] } = { 26'h0000000, _02_[4], gr_rd_ptr[0], _03_[0] };
  assign { _02_[31:5], _02_[0] } = { 27'h0000000, b_rd_ptr[0] };
  assign gr_rd_ptr[4] = b_rd_ptr[4];
endmodule

(* dynports =  1  *)
(* hdlname = "wr_ptr" *)
(* src = "rtl/wr_ptr.sv:3.1-21.10" *)
module \$paramod\wr_ptr\ADDR_WIDTH=s32'00000000000000000000000000000100 (wr_clk, wr_rst, wr_en, full, b_wr_ptr, gr_wr_ptr);
  (* src = "rtl/wr_ptr.sv:4.17-4.23" *)
  input wr_clk;
  wire wr_clk;
  (* src = "rtl/wr_ptr.sv:5.17-5.23" *)
  input wr_rst;
  wire wr_rst;
  (* src = "rtl/wr_ptr.sv:6.17-6.22" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/wr_ptr.sv:7.17-7.21" *)
  input full;
  wire full;
  (* src = "rtl/wr_ptr.sv:8.33-8.41" *)
  output [4:0] b_wr_ptr;
  reg [4:0] b_wr_ptr;
  (* src = "rtl/wr_ptr.sv:9.33-9.42" *)
  output [4:0] gr_wr_ptr;
  wire [4:0] gr_wr_ptr;
  (* src = "rtl/wr_ptr.sv:16.14-16.28" *)
  wire _00_;
  (* src = "rtl/wr_ptr.sv:16.23-16.28" *)
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _04_;
  (* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _05_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:12.1-19.4" *)
  always @(posedge wr_clk, negedge wr_rst)
    if (!wr_rst) b_wr_ptr[0] <= 1'h0;
    else if (_00_) b_wr_ptr[0] <= _03_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:12.1-19.4" *)
  always @(posedge wr_clk, negedge wr_rst)
    if (!wr_rst) b_wr_ptr[1] <= 1'h0;
    else if (_00_) b_wr_ptr[1] <= gr_wr_ptr[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:12.1-19.4" *)
  always @(posedge wr_clk, negedge wr_rst)
    if (!wr_rst) b_wr_ptr[2] <= 1'h0;
    else if (_00_) b_wr_ptr[2] <= _04_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:12.1-19.4" *)
  always @(posedge wr_clk, negedge wr_rst)
    if (!wr_rst) b_wr_ptr[3] <= 1'h0;
    else if (_00_) b_wr_ptr[3] <= _04_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/wr_ptr.sv:12.1-19.4" *)
  always @(posedge wr_clk, negedge wr_rst)
    if (!wr_rst) b_wr_ptr[4] <= 1'h0;
    else if (_00_) b_wr_ptr[4] <= _04_[4];
  assign _03_[0] = ~b_wr_ptr[0];
  assign _02_[2] = b_wr_ptr[2] &(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _02_[1];
  assign _02_[3] = _05_ &(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _02_[1];
  assign _05_ = b_wr_ptr[3] &(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  b_wr_ptr[2];
  assign _02_[1] = b_wr_ptr[1] &(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  b_wr_ptr[0];
  assign gr_wr_ptr[1] = b_wr_ptr[2] ^(* src = "rtl/wr_ptr.sv:20.20-20.46" *)  b_wr_ptr[1];
  assign gr_wr_ptr[2] = b_wr_ptr[3] ^(* src = "rtl/wr_ptr.sv:20.20-20.46" *)  b_wr_ptr[2];
  assign gr_wr_ptr[3] = b_wr_ptr[4] ^(* src = "rtl/wr_ptr.sv:20.20-20.46" *)  b_wr_ptr[3];
  assign gr_wr_ptr[0] = b_wr_ptr[1] ^(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  b_wr_ptr[0];
  assign _04_[2] = b_wr_ptr[2] ^(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _02_[1];
  assign _04_[3] = b_wr_ptr[3] ^(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _02_[2];
  assign _04_[4] = b_wr_ptr[4] ^(* src = "rtl/wr_ptr.sv:17.21-17.33|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _02_[3];
  assign _01_ = ~(* src = "rtl/wr_ptr.sv:16.23-16.28" *) full;
  assign _00_ = wr_en &(* src = "rtl/wr_ptr.sv:16.14-16.28" *)  _01_;
  assign _03_[31:1] = { 27'h0000000, b_wr_ptr[4:1] };
  assign { _04_[31:5], _04_[1:0] } = { 26'h0000000, _02_[4], gr_wr_ptr[0], _03_[0] };
  assign { _02_[31:5], _02_[0] } = { 27'h0000000, b_wr_ptr[0] };
  assign gr_wr_ptr[4] = b_wr_ptr[4];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/async_fifo.sv:2.1-102.10" *)
module async_fifo(wr_clk, wr_rst, wr_en, d_in, rd_clk, rd_rst_n, rd_en, d_out, full, empty);
  (* src = "rtl/async_fifo.sv:3.17-3.23" *)
  input wr_clk;
  wire wr_clk;
  (* src = "rtl/async_fifo.sv:4.17-4.23" *)
  input wr_rst;
  wire wr_rst;
  (* src = "rtl/async_fifo.sv:5.17-5.22" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/async_fifo.sv:6.34-6.38" *)
  input [8:0] d_in;
  wire [8:0] d_in;
  (* src = "rtl/async_fifo.sv:7.17-7.23" *)
  input rd_clk;
  wire rd_clk;
  (* src = "rtl/async_fifo.sv:8.17-8.25" *)
  input rd_rst_n;
  wire rd_rst_n;
  (* src = "rtl/async_fifo.sv:9.17-9.22" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/async_fifo.sv:10.35-10.40" *)
  output [8:0] d_out;
  reg [8:0] d_out;
  (* src = "rtl/async_fifo.sv:11.18-11.22" *)
  output full;
  wire full;
  (* src = "rtl/async_fifo.sv:12.18-12.23" *)
  output empty;
  wire empty;
  (* src = "rtl/async_fifo.sv:79.1-83.4" *)
  wire [3:0] _000_;
  (* src = "rtl/async_fifo.sv:79.1-83.4" *)
  wire [8:0] _001_;
  (* src = "rtl/async_fifo.sv:79.1-83.4" *)
  wire [8:0] _002_;
  wire [8:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [1:0] _032_;
  wire _033_;
  wire [1:0] _034_;
  wire [4:0] _035_;
  wire _036_;
  wire [3:0] _037_;
  wire _038_;
  wire _039_;
  (* src = "rtl/async_fifo.sv:101.72-101.134" *)
  wire _040_;
  (* src = "rtl/async_fifo.sv:87.9-87.24" *)
  wire _041_;
  (* src = "rtl/async_fifo.sv:80.18-80.23" *)
  wire _042_;
  wire [8:0] _043_;
  wire [8:0] _044_;
  wire [8:0] _045_;
  wire [8:0] _046_;
  wire [8:0] _047_;
  wire [8:0] _048_;
  wire [8:0] _049_;
  wire [8:0] _050_;
  wire [8:0] _051_;
  wire [8:0] _052_;
  wire [8:0] _053_;
  wire [8:0] _054_;
  wire [8:0] _055_;
  wire [8:0] _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  reg [8:0] \mem[0] ;
  reg [8:0] \mem[10] ;
  reg [8:0] \mem[11] ;
  reg [8:0] \mem[12] ;
  reg [8:0] \mem[13] ;
  reg [8:0] \mem[14] ;
  reg [8:0] \mem[15] ;
  reg [8:0] \mem[1] ;
  reg [8:0] \mem[2] ;
  reg [8:0] \mem[3] ;
  reg [8:0] \mem[4] ;
  reg [8:0] \mem[5] ;
  reg [8:0] \mem[6] ;
  reg [8:0] \mem[7] ;
  reg [8:0] \mem[8] ;
  reg [8:0] \mem[9] ;
  (* src = "rtl/async_fifo.sv:20.33-20.40" *)
  wire [3:0] rd_addr;
  (* src = "rtl/async_fifo.sv:15.22-15.30" *)
  (* unused_bits = "4" *)
  wire [4:0] rd_b_ptr;
  (* src = "rtl/async_fifo.sv:15.32-15.40" *)
  wire [4:0] rd_g_ptr;
  (* src = "rtl/async_fifo.sv:18.22-18.36" *)
  wire [4:0] rd_g_ptr_sync1;
  (* src = "rtl/async_fifo.sv:18.38-18.52" *)
  wire [4:0] rd_g_ptr_sync2;
  (* src = "rtl/async_fifo.sv:20.24-20.31" *)
  wire [3:0] wr_addr;
  (* src = "rtl/async_fifo.sv:14.22-14.30" *)
  (* unused_bits = "4" *)
  wire [4:0] wr_b_ptr;
  (* src = "rtl/async_fifo.sv:14.32-14.40" *)
  wire [4:0] wr_g_ptr;
  (* src = "rtl/async_fifo.sv:17.22-17.36" *)
  wire [4:0] wr_g_ptr_sync1;
  (* src = "rtl/async_fifo.sv:17.38-17.52" *)
  wire [4:0] wr_g_ptr_sync2;
  always @(posedge wr_clk)
    if (_063_) \mem[15] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_063_) \mem[15] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_062_) \mem[14] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_061_) \mem[13] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_060_) \mem[12] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_059_) \mem[11] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_058_) \mem[10] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_072_) \mem[9] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_071_) \mem[8] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_070_) \mem[7] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_069_) \mem[6] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_068_) \mem[5] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_067_) \mem[4] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_066_) \mem[3] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_065_) \mem[2] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_064_) \mem[1] [8] <= _001_[8];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [0] <= _001_[0];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [1] <= _001_[1];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [2] <= _001_[2];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [3] <= _001_[3];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [4] <= _001_[4];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [5] <= _001_[5];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [6] <= _001_[6];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [7] <= _001_[7];
  always @(posedge wr_clk)
    if (_057_) \mem[0] [8] <= _001_[8];
  always @(posedge rd_clk)
    if (_041_) d_out[0] <= _003_[0];
  always @(posedge rd_clk)
    if (_041_) d_out[1] <= _003_[1];
  always @(posedge rd_clk)
    if (_041_) d_out[2] <= _003_[2];
  always @(posedge rd_clk)
    if (_041_) d_out[3] <= _003_[3];
  always @(posedge rd_clk)
    if (_041_) d_out[4] <= _003_[4];
  always @(posedge rd_clk)
    if (_041_) d_out[5] <= _003_[5];
  always @(posedge rd_clk)
    if (_041_) d_out[6] <= _003_[6];
  always @(posedge rd_clk)
    if (_041_) d_out[7] <= _003_[7];
  always @(posedge rd_clk)
    if (_041_) d_out[8] <= _003_[8];
  assign _027_ = _011_ & _023_;
  assign _026_ = _009_ & _023_;
  assign _025_ = _007_ & _023_;
  assign _024_ = _004_ & _023_;
  assign _023_ = _000_[2] & _000_[3];
  assign _022_ = _011_ & _018_;
  assign _021_ = _009_ & _018_;
  assign _020_ = _007_ & _018_;
  assign _019_ = _004_ & _018_;
  assign _018_ = _030_ & _000_[3];
  assign _017_ = _011_ & _013_;
  assign _016_ = _009_ & _013_;
  assign _015_ = _007_ & _013_;
  assign _014_ = _004_ & _013_;
  assign _013_ = _000_[2] & _031_;
  assign _012_ = _011_ & _005_;
  assign _011_ = _000_[0] & _000_[1];
  assign _010_ = _009_ & _005_;
  assign _009_ = _028_ & _000_[1];
  assign _008_ = _007_ & _005_;
  assign _007_ = _000_[0] & _029_;
  assign _006_ = _004_ & _005_;
  assign _005_ = _030_ & _031_;
  assign _004_ = _028_ & _029_;
  assign _035_[0] = rd_g_ptr[0] ^(* src = "rtl/async_fifo.sv:94.17-94.43" *)  wr_g_ptr_sync2[0];
  assign _035_[1] = rd_g_ptr[1] ^(* src = "rtl/async_fifo.sv:94.17-94.43" *)  wr_g_ptr_sync2[1];
  assign _035_[2] = rd_g_ptr[2] ^(* src = "rtl/async_fifo.sv:94.17-94.43" *)  wr_g_ptr_sync2[2];
  assign _035_[3] = rd_g_ptr[3] ^(* src = "rtl/async_fifo.sv:94.17-94.43" *)  wr_g_ptr_sync2[3];
  assign _035_[4] = rd_g_ptr[4] ^(* src = "rtl/async_fifo.sv:94.17-94.43" *)  wr_g_ptr_sync2[4];
  assign _036_ = wr_g_ptr[4] ^(* src = "rtl/async_fifo.sv:101.16-101.66" *)  rd_g_ptr_sync2[4];
  assign _037_[0] = wr_g_ptr[0] ^(* src = "rtl/async_fifo.sv:101.72-101.134" *)  rd_g_ptr_sync2[0];
  assign _037_[1] = wr_g_ptr[1] ^(* src = "rtl/async_fifo.sv:101.72-101.134" *)  rd_g_ptr_sync2[1];
  assign _037_[2] = wr_g_ptr[2] ^(* src = "rtl/async_fifo.sv:101.72-101.134" *)  rd_g_ptr_sync2[2];
  assign _037_[3] = wr_g_ptr[3] ^(* src = "rtl/async_fifo.sv:101.72-101.134" *)  rd_g_ptr_sync2[3];
  assign _057_ = _006_ & _002_[0];
  assign _064_ = _008_ & _002_[0];
  assign _065_ = _010_ & _002_[0];
  assign _066_ = _012_ & _002_[0];
  assign _067_ = _014_ & _002_[0];
  assign _068_ = _015_ & _002_[0];
  assign _069_ = _016_ & _002_[0];
  assign _070_ = _017_ & _002_[0];
  assign _071_ = _019_ & _002_[0];
  assign _072_ = _020_ & _002_[0];
  assign _058_ = _021_ & _002_[0];
  assign _059_ = _022_ & _002_[0];
  assign _060_ = _024_ & _002_[0];
  assign _061_ = _025_ & _002_[0];
  assign _062_ = _026_ & _002_[0];
  assign _063_ = _027_ & _002_[0];
  assign _032_[0] = _035_[0] |(* src = "rtl/async_fifo.sv:94.17-94.43" *)  _035_[1];
  assign _032_[1] = _035_[2] |(* src = "rtl/async_fifo.sv:94.17-94.43" *)  _035_[3];
  assign _033_ = _032_[0] |(* src = "rtl/async_fifo.sv:94.17-94.43" *)  _032_[1];
  assign _038_ = _033_ |(* src = "rtl/async_fifo.sv:94.17-94.43" *)  _035_[4];
  assign _034_[0] = _037_[0] |(* src = "rtl/async_fifo.sv:101.72-101.134" *)  _037_[1];
  assign _034_[1] = _037_[2] |(* src = "rtl/async_fifo.sv:101.72-101.134" *)  _037_[3];
  assign _039_ = _034_[0] |(* src = "rtl/async_fifo.sv:101.72-101.134" *)  _034_[1];
  assign _042_ = ~(* src = "rtl/async_fifo.sv:80.18-80.23" *) full;
  assign empty = ~(* src = "rtl/async_fifo.sv:94.17-94.43" *) _038_;
  assign _040_ = ~(* src = "rtl/async_fifo.sv:101.72-101.134" *) _039_;
  assign _002_[0] = wr_en &(* src = "rtl/async_fifo.sv:80.9-80.23" *)  _042_;
  assign _041_ = rd_en &(* src = "rtl/async_fifo.sv:87.9-87.24" *)  _038_;
  assign full = _036_ &(* src = "rtl/async_fifo.sv:101.15-101.135" *)  _040_;
  assign _055_[0] = rd_b_ptr[0] ? \mem[13] [0] : \mem[12] [0];
  assign _055_[1] = rd_b_ptr[0] ? \mem[13] [1] : \mem[12] [1];
  assign _055_[2] = rd_b_ptr[0] ? \mem[13] [2] : \mem[12] [2];
  assign _055_[3] = rd_b_ptr[0] ? \mem[13] [3] : \mem[12] [3];
  assign _055_[4] = rd_b_ptr[0] ? \mem[13] [4] : \mem[12] [4];
  assign _055_[5] = rd_b_ptr[0] ? \mem[13] [5] : \mem[12] [5];
  assign _055_[6] = rd_b_ptr[0] ? \mem[13] [6] : \mem[12] [6];
  assign _055_[7] = rd_b_ptr[0] ? \mem[13] [7] : \mem[12] [7];
  assign _055_[8] = rd_b_ptr[0] ? \mem[13] [8] : \mem[12] [8];
  assign _054_[0] = rd_b_ptr[0] ? \mem[11] [0] : \mem[10] [0];
  assign _054_[1] = rd_b_ptr[0] ? \mem[11] [1] : \mem[10] [1];
  assign _054_[2] = rd_b_ptr[0] ? \mem[11] [2] : \mem[10] [2];
  assign _054_[3] = rd_b_ptr[0] ? \mem[11] [3] : \mem[10] [3];
  assign _054_[4] = rd_b_ptr[0] ? \mem[11] [4] : \mem[10] [4];
  assign _054_[5] = rd_b_ptr[0] ? \mem[11] [5] : \mem[10] [5];
  assign _054_[6] = rd_b_ptr[0] ? \mem[11] [6] : \mem[10] [6];
  assign _054_[7] = rd_b_ptr[0] ? \mem[11] [7] : \mem[10] [7];
  assign _054_[8] = rd_b_ptr[0] ? \mem[11] [8] : \mem[10] [8];
  assign _053_[0] = rd_b_ptr[0] ? \mem[9] [0] : \mem[8] [0];
  assign _053_[1] = rd_b_ptr[0] ? \mem[9] [1] : \mem[8] [1];
  assign _053_[2] = rd_b_ptr[0] ? \mem[9] [2] : \mem[8] [2];
  assign _053_[3] = rd_b_ptr[0] ? \mem[9] [3] : \mem[8] [3];
  assign _053_[4] = rd_b_ptr[0] ? \mem[9] [4] : \mem[8] [4];
  assign _053_[5] = rd_b_ptr[0] ? \mem[9] [5] : \mem[8] [5];
  assign _053_[6] = rd_b_ptr[0] ? \mem[9] [6] : \mem[8] [6];
  assign _053_[7] = rd_b_ptr[0] ? \mem[9] [7] : \mem[8] [7];
  assign _053_[8] = rd_b_ptr[0] ? \mem[9] [8] : \mem[8] [8];
  assign _052_[0] = rd_b_ptr[0] ? \mem[7] [0] : \mem[6] [0];
  assign _052_[1] = rd_b_ptr[0] ? \mem[7] [1] : \mem[6] [1];
  assign _052_[2] = rd_b_ptr[0] ? \mem[7] [2] : \mem[6] [2];
  assign _052_[3] = rd_b_ptr[0] ? \mem[7] [3] : \mem[6] [3];
  assign _052_[4] = rd_b_ptr[0] ? \mem[7] [4] : \mem[6] [4];
  assign _052_[5] = rd_b_ptr[0] ? \mem[7] [5] : \mem[6] [5];
  assign _052_[6] = rd_b_ptr[0] ? \mem[7] [6] : \mem[6] [6];
  assign _052_[7] = rd_b_ptr[0] ? \mem[7] [7] : \mem[6] [7];
  assign _052_[8] = rd_b_ptr[0] ? \mem[7] [8] : \mem[6] [8];
  assign _051_[0] = rd_b_ptr[0] ? \mem[5] [0] : \mem[4] [0];
  assign _051_[1] = rd_b_ptr[0] ? \mem[5] [1] : \mem[4] [1];
  assign _051_[2] = rd_b_ptr[0] ? \mem[5] [2] : \mem[4] [2];
  assign _051_[3] = rd_b_ptr[0] ? \mem[5] [3] : \mem[4] [3];
  assign _051_[4] = rd_b_ptr[0] ? \mem[5] [4] : \mem[4] [4];
  assign _051_[5] = rd_b_ptr[0] ? \mem[5] [5] : \mem[4] [5];
  assign _051_[6] = rd_b_ptr[0] ? \mem[5] [6] : \mem[4] [6];
  assign _051_[7] = rd_b_ptr[0] ? \mem[5] [7] : \mem[4] [7];
  assign _051_[8] = rd_b_ptr[0] ? \mem[5] [8] : \mem[4] [8];
  assign _050_[0] = rd_b_ptr[0] ? \mem[3] [0] : \mem[2] [0];
  assign _050_[1] = rd_b_ptr[0] ? \mem[3] [1] : \mem[2] [1];
  assign _050_[2] = rd_b_ptr[0] ? \mem[3] [2] : \mem[2] [2];
  assign _050_[3] = rd_b_ptr[0] ? \mem[3] [3] : \mem[2] [3];
  assign _050_[4] = rd_b_ptr[0] ? \mem[3] [4] : \mem[2] [4];
  assign _050_[5] = rd_b_ptr[0] ? \mem[3] [5] : \mem[2] [5];
  assign _050_[6] = rd_b_ptr[0] ? \mem[3] [6] : \mem[2] [6];
  assign _050_[7] = rd_b_ptr[0] ? \mem[3] [7] : \mem[2] [7];
  assign _050_[8] = rd_b_ptr[0] ? \mem[3] [8] : \mem[2] [8];
  assign _049_[0] = rd_b_ptr[0] ? \mem[1] [0] : \mem[0] [0];
  assign _049_[1] = rd_b_ptr[0] ? \mem[1] [1] : \mem[0] [1];
  assign _049_[2] = rd_b_ptr[0] ? \mem[1] [2] : \mem[0] [2];
  assign _049_[3] = rd_b_ptr[0] ? \mem[1] [3] : \mem[0] [3];
  assign _049_[4] = rd_b_ptr[0] ? \mem[1] [4] : \mem[0] [4];
  assign _049_[5] = rd_b_ptr[0] ? \mem[1] [5] : \mem[0] [5];
  assign _049_[6] = rd_b_ptr[0] ? \mem[1] [6] : \mem[0] [6];
  assign _049_[7] = rd_b_ptr[0] ? \mem[1] [7] : \mem[0] [7];
  assign _049_[8] = rd_b_ptr[0] ? \mem[1] [8] : \mem[0] [8];
  assign _048_[0] = rd_b_ptr[1] ? _056_[0] : _055_[0];
  assign _048_[1] = rd_b_ptr[1] ? _056_[1] : _055_[1];
  assign _048_[2] = rd_b_ptr[1] ? _056_[2] : _055_[2];
  assign _048_[3] = rd_b_ptr[1] ? _056_[3] : _055_[3];
  assign _048_[4] = rd_b_ptr[1] ? _056_[4] : _055_[4];
  assign _048_[5] = rd_b_ptr[1] ? _056_[5] : _055_[5];
  assign _048_[6] = rd_b_ptr[1] ? _056_[6] : _055_[6];
  assign _048_[7] = rd_b_ptr[1] ? _056_[7] : _055_[7];
  assign _048_[8] = rd_b_ptr[1] ? _056_[8] : _055_[8];
  assign _047_[0] = rd_b_ptr[1] ? _054_[0] : _053_[0];
  assign _047_[1] = rd_b_ptr[1] ? _054_[1] : _053_[1];
  assign _047_[2] = rd_b_ptr[1] ? _054_[2] : _053_[2];
  assign _047_[3] = rd_b_ptr[1] ? _054_[3] : _053_[3];
  assign _047_[4] = rd_b_ptr[1] ? _054_[4] : _053_[4];
  assign _047_[5] = rd_b_ptr[1] ? _054_[5] : _053_[5];
  assign _047_[6] = rd_b_ptr[1] ? _054_[6] : _053_[6];
  assign _047_[7] = rd_b_ptr[1] ? _054_[7] : _053_[7];
  assign _047_[8] = rd_b_ptr[1] ? _054_[8] : _053_[8];
  assign _046_[0] = rd_b_ptr[1] ? _052_[0] : _051_[0];
  assign _046_[1] = rd_b_ptr[1] ? _052_[1] : _051_[1];
  assign _046_[2] = rd_b_ptr[1] ? _052_[2] : _051_[2];
  assign _046_[3] = rd_b_ptr[1] ? _052_[3] : _051_[3];
  assign _046_[4] = rd_b_ptr[1] ? _052_[4] : _051_[4];
  assign _046_[5] = rd_b_ptr[1] ? _052_[5] : _051_[5];
  assign _046_[6] = rd_b_ptr[1] ? _052_[6] : _051_[6];
  assign _046_[7] = rd_b_ptr[1] ? _052_[7] : _051_[7];
  assign _046_[8] = rd_b_ptr[1] ? _052_[8] : _051_[8];
  assign _045_[0] = rd_b_ptr[1] ? _050_[0] : _049_[0];
  assign _045_[1] = rd_b_ptr[1] ? _050_[1] : _049_[1];
  assign _045_[2] = rd_b_ptr[1] ? _050_[2] : _049_[2];
  assign _045_[3] = rd_b_ptr[1] ? _050_[3] : _049_[3];
  assign _045_[4] = rd_b_ptr[1] ? _050_[4] : _049_[4];
  assign _045_[5] = rd_b_ptr[1] ? _050_[5] : _049_[5];
  assign _045_[6] = rd_b_ptr[1] ? _050_[6] : _049_[6];
  assign _045_[7] = rd_b_ptr[1] ? _050_[7] : _049_[7];
  assign _045_[8] = rd_b_ptr[1] ? _050_[8] : _049_[8];
  assign _044_[0] = rd_b_ptr[2] ? _048_[0] : _047_[0];
  assign _044_[1] = rd_b_ptr[2] ? _048_[1] : _047_[1];
  assign _044_[2] = rd_b_ptr[2] ? _048_[2] : _047_[2];
  assign _044_[3] = rd_b_ptr[2] ? _048_[3] : _047_[3];
  assign _044_[4] = rd_b_ptr[2] ? _048_[4] : _047_[4];
  assign _044_[5] = rd_b_ptr[2] ? _048_[5] : _047_[5];
  assign _044_[6] = rd_b_ptr[2] ? _048_[6] : _047_[6];
  assign _044_[7] = rd_b_ptr[2] ? _048_[7] : _047_[7];
  assign _044_[8] = rd_b_ptr[2] ? _048_[8] : _047_[8];
  assign _043_[0] = rd_b_ptr[2] ? _046_[0] : _045_[0];
  assign _043_[1] = rd_b_ptr[2] ? _046_[1] : _045_[1];
  assign _043_[2] = rd_b_ptr[2] ? _046_[2] : _045_[2];
  assign _043_[3] = rd_b_ptr[2] ? _046_[3] : _045_[3];
  assign _043_[4] = rd_b_ptr[2] ? _046_[4] : _045_[4];
  assign _043_[5] = rd_b_ptr[2] ? _046_[5] : _045_[5];
  assign _043_[6] = rd_b_ptr[2] ? _046_[6] : _045_[6];
  assign _043_[7] = rd_b_ptr[2] ? _046_[7] : _045_[7];
  assign _043_[8] = rd_b_ptr[2] ? _046_[8] : _045_[8];
  assign _003_[0] = rd_b_ptr[3] ? _044_[0] : _043_[0];
  assign _003_[1] = rd_b_ptr[3] ? _044_[1] : _043_[1];
  assign _003_[2] = rd_b_ptr[3] ? _044_[2] : _043_[2];
  assign _003_[3] = rd_b_ptr[3] ? _044_[3] : _043_[3];
  assign _003_[4] = rd_b_ptr[3] ? _044_[4] : _043_[4];
  assign _003_[5] = rd_b_ptr[3] ? _044_[5] : _043_[5];
  assign _003_[6] = rd_b_ptr[3] ? _044_[6] : _043_[6];
  assign _003_[7] = rd_b_ptr[3] ? _044_[7] : _043_[7];
  assign _003_[8] = rd_b_ptr[3] ? _044_[8] : _043_[8];
  assign _001_[0] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[0] : 1'hx;
  assign _001_[1] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[1] : 1'hx;
  assign _001_[2] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[2] : 1'hx;
  assign _001_[3] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[3] : 1'hx;
  assign _001_[4] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[4] : 1'hx;
  assign _001_[5] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[5] : 1'hx;
  assign _001_[6] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[6] : 1'hx;
  assign _001_[7] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[7] : 1'hx;
  assign _001_[8] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) d_in[8] : 1'hx;
  assign _000_[0] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) wr_b_ptr[0] : 1'hx;
  assign _000_[1] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) wr_b_ptr[1] : 1'hx;
  assign _000_[2] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) wr_b_ptr[2] : 1'hx;
  assign _000_[3] = _002_[0] ? (* src = "rtl/async_fifo.sv:80.9-80.23|rtl/async_fifo.sv:80.5-82.8" *) wr_b_ptr[3] : 1'hx;
  assign _056_[0] = rd_b_ptr[0] ? \mem[15] [0] : \mem[14] [0];
  assign _056_[1] = rd_b_ptr[0] ? \mem[15] [1] : \mem[14] [1];
  assign _056_[2] = rd_b_ptr[0] ? \mem[15] [2] : \mem[14] [2];
  assign _056_[3] = rd_b_ptr[0] ? \mem[15] [3] : \mem[14] [3];
  assign _056_[4] = rd_b_ptr[0] ? \mem[15] [4] : \mem[14] [4];
  assign _056_[5] = rd_b_ptr[0] ? \mem[15] [5] : \mem[14] [5];
  assign _056_[6] = rd_b_ptr[0] ? \mem[15] [6] : \mem[14] [6];
  assign _056_[7] = rd_b_ptr[0] ? \mem[15] [7] : \mem[14] [7];
  assign _056_[8] = rd_b_ptr[0] ? \mem[15] [8] : \mem[14] [8];
  assign _031_ = ~_000_[3];
  assign _030_ = ~_000_[2];
  assign _029_ = ~_000_[1];
  assign _028_ = ~_000_[0];
  (* src = "rtl/async_fifo.sv:23.22-31.2" *)
  \$paramod\rd_ptr\ADDR_WIDTH=s32'00000000000000000000000000000100  rd_block (
    .b_rd_ptr(rd_b_ptr),
    .empty(empty),
    .gr_rd_ptr(rd_g_ptr),
    .rd_clk(rd_clk),
    .rd_en(rd_en),
    .rd_rst_n(rd_rst_n)
  );
  (* src = "rtl/async_fifo.sv:44.27-50.2" *)
  \$paramod\ff_sync\WIDTH=s32'00000000000000000000000000000101  sync1 (
    .clk(rd_clk),
    .din(wr_g_ptr),
    .dout(wr_g_ptr_sync1),
    .rst_n(rd_rst_n)
  );
  (* src = "rtl/async_fifo.sv:51.27-56.2" *)
  \$paramod\ff_sync\WIDTH=s32'00000000000000000000000000000101  sync2 (
    .clk(rd_clk),
    .din(wr_g_ptr_sync1),
    .dout(wr_g_ptr_sync2),
    .rst_n(rd_rst_n)
  );
  (* src = "rtl/async_fifo.sv:60.27-65.2" *)
  \$paramod\ff_sync\WIDTH=s32'00000000000000000000000000000101  sync3 (
    .clk(wr_clk),
    .din(rd_g_ptr),
    .dout(rd_g_ptr_sync1),
    .rst_n(wr_rst)
  );
  (* src = "rtl/async_fifo.sv:66.27-71.2" *)
  \$paramod\ff_sync\WIDTH=s32'00000000000000000000000000000101  sync4 (
    .clk(wr_clk),
    .din(rd_g_ptr_sync1),
    .dout(rd_g_ptr_sync2),
    .rst_n(wr_rst)
  );
  (* src = "rtl/async_fifo.sv:33.22-40.2" *)
  \$paramod\wr_ptr\ADDR_WIDTH=s32'00000000000000000000000000000100  wr_block (
    .b_wr_ptr(wr_b_ptr),
    .full(full),
    .gr_wr_ptr(wr_g_ptr),
    .wr_clk(wr_clk),
    .wr_en(wr_en),
    .wr_rst(wr_rst)
  );
  assign _002_[8:1] = { _002_[0], _002_[0], _002_[0], _002_[0], _002_[0], _002_[0], _002_[0], _002_[0] };
  assign rd_addr = rd_b_ptr[3:0];
  assign wr_addr = wr_b_ptr[3:0];
endmodule
